name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build projects
        run: './gradlew build --no-daemon --stacktrace --console=plain --rerun-tasks'

      - name: Build JAR
        run: './gradlew jar --no-daemon --stacktrace --console=plain --rerun-tasks'